### ISSUE TITLE
apply algorithms to new variables

### ISSUE THREAD

**Issue by RosaMGini** [VAC4EU/CVM#27]
-) include in parameters 06_algorithm the notion of conceptsets associated to a variable
-) handle the case when the algorithm is trivial ('OR') and the case when the algorithm is non trivial (in the current specifications, only one type of algorithm is needed A AND B within a timeframe, whicbis already implemented in the parameter file using the parameter selectionrule_direction_seccomp)

**Comment by RosaMGini** [comment]
@cduransalinas, @DavideMessinaARS and i are trying to understand how the algorithms for variables are defined in [this folder](https://vac4eu.sharepoint.com/sites/Toolbox/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FToolbox%2FShared%20Documents%2F08%20Event%20%26%20Covariate%20definitions%2FAESI%20%26%20Covariate%20definition%20forms%20%26%20Algorithms&viewid=8c361874%2D61d2%2D40c1%2Db4cf%2De3e1de20abec) in the VAC4EU SP. we think we are understanding [this file](https://vac4eu.sharepoint.com/:x:/r/sites/Toolbox/_layouts/15/Doc.aspx?sourcedoc=%7BBB94A2A0-E57A-4E4D-94F2-A080F6A251CB%7D&file=VAC4EU%20PASS%20CovidVaccineMonitoringVariables.xlsx&action=default&mobileredirect=true), but we are not sure, and we don't know if it's the most up to date. 

is there any documentation on what each spreadsheet means? we have seen [this instructions document](https://vac4eu.sharepoint.com/:w:/r/sites/Toolbox/_layouts/15/Doc.aspx?sourcedoc=%7B7E18F1CC-3B14-4C63-AE25-533394CD1112%7D&file=Instructions%20for%20creation%20of%20diagnosis%C2%A0and%20medicines%20list%20.docx&action=default&mobileredirect=true), but it is also not completely clear. or, can we perhaps organize a call for you to explain how you suggest for us to find specifically indications to implement the variables (AESIs, negative outcomes, covariates) of CVM?

**Comment by cduransalinas** [comment]
Let's organise a call:
Tuesday 2/8 : 11 am
Wednesday 3/8: any moment from 10am to 13pm, 16pm

**Comment by RosaMGini** [comment]
the ingredients are the following

1) in [this folder](https://vac4eu.sharepoint.com/sites/Toolbox/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FToolbox%2FShared%20Documents%2F08%20Event%20%26%20Covariate%20definitions%2FDiagnosisCodeSheet%2FStudy%20specific%20code%20lists%2FROC20&viewid=8c361874%2D61d2%2D40c1%2Db4cf%2De3e1de20abec), a unique list of diagnostic codes, grouped in conceptsets, the name of the conceptset is composed by 3 columns system + "_" + event_abbreviation + "_" + type, the domain is diagnosis

2) a [this folder](https://vac4eu.sharepoint.com/sites/Toolbox/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FToolbox%2FShared%20Documents%2F08%20Event%20%26%20Covariate%20definitions%2FDiagnosisCodeSheet%2FStudy%20specific%20code%20lists%2FROC20&viewid=8c361874%2D61d2%2D40c1%2Db4cf%2De3e1de20abec),unique list of drug codes, grouped in conceptsets, the name of the conceptset is in the column drug_proxy

3) the conceptsets above are ingredient in a list of variables that carlos is going to prepare. in this list, each row is a variable, and columns specify both the role (whether the variable is an AESI, a covariate, a negative outcome), and the way of computing: 
  - if algorithm = FALSE and algorithm_input = FALSE, then the variable is just computed using the corresponding conceptset which has the same name
  - if algorithm = TRUE and algorithm_input = FALSE, then the variable is just computed using an algorithm that is specified in the tab "Algorithm New Variables" of the same spreadsheet, corresponding to the same name in the column "New Variable Name"
  -  if algorithm = FALSE and algorithm_input = TRUE, then the variable is still just computed, but we also know that it is an ingredient in another variable, also specified in the tab "Algorithm New Variables" of the same spreadsheet, corresponding to the same name in the column "New Variable Name"

The syntax of the "Algorithm New Variables" is simple: most algorithms are just 'OR' juxtapositions of a list of conceptsets, and then there are few variables with secondary components

**Comment by RosaMGini** [comment]
Note that in the diagnostic codelist, codes are classified as 'narrow' and 'possible'. It is implicit that only 'narrow' codes enter the algorithms in the current version

**Comment by RosaMGini** [comment]
thanks @cduransalinas for sharing the diagnostic codelist file, i link it [here](https://teamitresearch.sharepoint.com/:x:/r/sites/EMAtenderROC20/_layouts/15/Doc.aspx?sourcedoc=%7B6E752FBF-ECD0-4FF6-8B6E-21064A934024%7D&file=20220727_V2_ROC20_full_codelist.xlsx&action=default&mobileredirect=true) for tracking

**Comment by cduransalinas** [comment]
@RosaMGini, @DavideMessinaARS 
the list of VARIABLES, ALGORITHMS and DRUG PROXIES are in [this link ](https://teamitresearch.sharepoint.com/:x:/r/sites/EMAtenderROC20/Shared%20Documents/08.%20EHR%20studies/00.%20Readiness%20Phase/04.%20Script%20development/[Variables_ALG_DP_ROC20_July22.xlsx](https://teamitresearch.sharepoint.com/:x:/r/sites/EMAtenderROC20/Shared%20Documents/08.%20EHR%20studies/00.%20Readiness%20Phase/04.%20Script%20development/Variables_ALG_DP_ROC20_July22.xlsx?d=w604e109797264df09f1297a0f466ab66&csf=1&web=1&e=XCT4Pt)?d=w604e109797264df09f1297a0f466ab66&csf=1&web=1&e=XCT4Pt).

In the Variables' sheet you will see two unfilled rows, I will complete them.
In the same sheet, at the end, you will also see to variables in grey colour. It means that the corresponding list of codes for these variables are not included in the full list of codes. They will be included in a next round. Thank you.

**Comment by cduransalinas** [comment]
In the Drug proxy sheet, I tried to use a similar format as in the variables' sheet (columns for AESI, COV, Algorithm and Algorithm input).
