### ISSUE TITLE
update vaccine variables

### ISSUE THREAD

**Issue by RosaMGini** [VAC4EU/CVM#29]
update 4th dose and vaccine manufacturer list

**Comment by DavideMessinaARS** [comment]
@cduransalinas I've read in the SAP this passage about the cleaning of vaccines doses records:

    Vaccines table cleaning: order chronologically and assign an imputed dose if vx_dose is empty,
    distance between dose 1 and 2 should be 15 days, between dose 3 and 2 at least 60 days
    and between dose 4 and 3 at least 60 days.
    (Section 8.5)

This is drastically different from how we have done things until now and I wanted to ask your opinion.
I will explain now what are the main points of the algorithm in the most recent script:

1) Check if a record is duplicated by checking person_id, vx_dose, vx_manufacturer and derived_date
    - NOTE: derived_date = date/vx_record_date
2) Check if a record does not have derived_date associated to it
3) Check if a record has date before start_COVID_vaccination_date
    - NOTE: CPRD = 06/12/2020, others = 27/12/2020
4) Check distances, **in order of calendar time**, between first/second and second/third doses are more or equal than n days
    - NOTE: 1st-2nd n=14 ///// 2nd-3rd n=60
5) The dose number is then imputed for the still remaining doses by ordering them by calendar time. **All of them, not just the missing ones**.
6) Calculation of count of concordant/discordant doses for quality check statistics
7) Check if a record has an imputed dose number of more than 3

Should we then impute vaccine dose numbers only if the original are empty?
If yes, what should I do in case there are missing records? (EX: 1st and 3rd doses but not 2nd)

**Comment by cduransalinas** [comment]
We agree with the proposal: steps 1 to 6 
In step 7 > more than 4.
