### ISSUE TITLE
Inclusion of persons having multiple spans of observation periods

### ISSUE THREAD

**Issue by RosaMGini** [VAC4EU/CVM#31]
when a person has multiple spans of observation periods, one long enough to be included (>365 days) and the other too short to be included, but incorporating one vaccination (the first??) what should we do? according to the SAP as it is now, this person would be excluded, because the second spell it too short, and the first is not the one with the 'first' vaccination observed

![image](https://user-images.githubusercontent.com/43318382/177280105-359d4248-8be8-4208-8614-8dec653bf6dc.png)

**Comment by cduransalinas** [comment]
The person referred in this example should be excluded (SAP _8.3 Spells (observation periods_)).

**Comment by RosaMGini** [comment]
Ok, but I suggest we make a descriptive of persons with multiple spells that are discarded this way, because in parinciple we are discarding persons based on an information in the future (we discard the first spell because in the future there will be a second spell with vaccination and too short), do you agree?

**Comment by RosaMGini** [comment]
also, figure 4 on page 57 of the SAP is no longer valid, because the requirement that the chosen spell includes the study start date (now 1st january 2019) is no longer valid. correct? so patient 5 in the figure is now included, with start date = op_start_date + 365. correct?
