### ISSUE TITLE
Errors in 05-T3-10_count_events_windows

### ISSUE THREAD

**Issue by elisacm98** [VAC4EU/CVM#35]
Hi,

We have the following errors running the CountPersonTime function:

![error_05_T3_10](https://user-images.githubusercontent.com/102016400/199975088-d8651533-ab09-4591-a265-42d0ea756625.jpg)
![error_05_T3_10_recurrent](https://user-images.githubusercontent.com/102016400/199975105-bb6b049e-8422-4dcb-8ba3-fa7317ddffec.jpg)

Let me know if you need more information. Thanks for your help.

**Comment by DavideMessinaARS** [comment]
sorry [elisacm98](https://github.com/elisacm98) but which DAP are you part of?
I don't have your GitHub username in SharePoint's list of ROC20 GitHub accounts.

https://teamitresearch.sharepoint.com/:x:/r/sites/EMAtenderROC20/_layouts/15/doc2.aspx?sourcedoc=%7BA49D273A-3C4E-4BA2-B00C-D562DDD5925D%7D&file=ROC20-GitHub%20accounts.xlsx&action=default&mobileredirect=true&cid=4c9f2756-9390-42a3-9d6e-230d93d25e7a

Anyway, can you open "D3_study_population_by_window_and_dose" found in "g_intermediate" and check if it seems ok?

**Comment by elisacm98** [comment]
I am from FISABIO team. 

I checked "D3_study_population_by_window_and_dose" and it seems ok to me.

**Comment by DavideMessinaARS** [comment]
Can we schedule a call? Today I'm available until 14. You?

**Comment by elisacm98** [comment]
Can we schedule a call at 13? Please, send me the link to this email: elisa.correcher@ucv.es. It isn't the mail that appears in the contact list, but I'm having problems with that account.

**Comment by elisacm98** [comment]
Scripts 05_T3_10_count_events_windows.R and 05_T3_11_aggregate_events_windows.R have run perfectly. Thanks for your help!
