### ISSUE TITLE
Error messages in step 12_2

### ISSUE THREAD

**Issue by DavideMessinaARS** [VAC4EU/CVM#6]
Step 12_2 works but at the same time prints a lot of error messages. 

Would it be possible to remove them if they are irrelevant?
I know the script runs just fine but the other DAPS might not be able to and shouldn't differentiate between these errors and important ones.

Thanks

**Comment by svetlanabelitser** [comment]
I will try now.

**Comment by svetlanabelitser** [comment]
Done.

**Comment by DavideMessinaARS** [comment]
Merged to main in https://github.com/VAC4EU/CVM/pull/7 and https://github.com/VAC4EU/CVM/pull/8
